# -*- coding: utf-8 -*-
"""keras_segmentation_cli_example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kpy4QGFZ2ZHm69mPfkmLSUes8kj6Bjyi

# Example of CLI interface of keras_segmentation

### Install the package
"""

! pip install --upgrade git+https://github.com/divamgupta/image-segmentation-keras

"""### Download the dataset"""

! wget https://github.com/divamgupta/datasets/releases/download/seg/dataset1.zip && unzip dataset1.zip

"""### Start training"""

! python -m keras_segmentation train --checkpoints_path="/tmp/vgg_unet_1" --train_images="dataset1/images_prepped_train/" --train_annotations="dataset1/annotations_prepped_train/" --val_images="dataset1/images_prepped_test/" --val_annotations="dataset1/annotations_prepped_test/" --n_classes=50 --input_height=320 --input_width=640 --model_name="vgg_unet" --epochs=5

"""### Predict output on test samples"""

! python -m keras_segmentation predict --checkpoints_path="/tmp/vgg_unet_1" --input_path="dataset1/images_prepped_test/0016E5_07959.png" --output_path="./out24.png"

"""### Now lets see the predicted **output**"""

from IPython.display import Image
Image('out24.png')

