# -*- coding: utf-8 -*-
"""Python_Knee_Keras_Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y-x4NyoYm9QVl38kSKr6HVAUbs0Rhs8P

### Install the package
"""

! pip install git+https://github.com/divamgupta/image-segmentation-keras

"""### Download the dataset"""

! wget https://github.com/divamgupta/datasets/releases/download/seg/dataset1.zip && unzip dataset1.zip

"""### Initialize the model"""

from keras_segmentation.models.unet import vgg_unet

model = vgg_unet(n_classes=50 ,  input_height=320, input_width=640  )

"""### Train the model"""

model.train(
    train_images =  "dataset1/images_prepped_train/",
    train_annotations = "dataset1/annotations_prepped_train/",
    checkpoints_path = "/tmp/vgg_unet_1" , epochs=5
)

out = model.predict_segmentation(
    inp="dataset1/images_prepped_test/0016E5_07965.png",
    out_fname="/tmp/out.png"
)

out = model.predict_segmentation(
    inp="KNEE CORONAL.jpg",
    out_fname="/tmp/out.png"
)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

import matplotlib
import matplotlib.pyplot as plt

plt.imshow(out)

from IPython.display import Image
Image('/tmp/out.png')



#o = model.predict_segmentation(
#    inp="KNEE CORONAL.jpg",
#    out_fname="/tmp/out.png" , overlay_img=True, show_legends=True,
#    class_names = [ "Sky",    "Building", "Pole","Road","Pavement","Tree","SignSymbol", "Fence", "Car","Pedestrian", "Bicyclist"]

#)

o = model.predict_segmentation(
    inp="KNEE CORONAL.jpg",
    out_fname="/tmp/out.png" , overlay_img=True, show_legends=True,
    class_names = [ "Sky",    "Building", "Pole"]

)

from IPython.display import Image
Image('/tmp/out.png')







